openapi: 3.0.4
info:
  title: Food-Catalog-Api - Subset
  description: An Api that allows interaction with food items
  version: v1
servers:
  - url: https://food-catalog-api-dev.azurewebsites.net
paths:
  /Food:
    get:
      tags:
        - Food
      summary: Gets all food
      description: Gets all food
      operationId: GetFood
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
                    name:
                      type: string
                    price:
                      type: number
                      format: double
                    inStock:
                      type: integer
                      format: int32
                    minStock:
                      type: integer
                      description: Minimum amount to keep in stock
                      format: int32
                    pictureUrl:
                      type: string
                    code:
                      type: string
                    description:
                      type: string
                  additionalProperties: false
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
                    name:
                      type: string
                    price:
                      type: number
                      format: double
                    inStock:
                      type: integer
                      format: int32
                    minStock:
                      type: integer
                      description: Minimum amount to keep in stock
                      format: int32
                    pictureUrl:
                      type: string
                    code:
                      type: string
                    description:
                      type: string
                  additionalProperties: false
            text/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
                    name:
                      type: string
                    price:
                      type: number
                      format: double
                    inStock:
                      type: integer
                      format: int32
                    minStock:
                      type: integer
                      description: Minimum amount to keep in stock
                      format: int32
                    pictureUrl:
                      type: string
                    code:
                      type: string
                    description:
                      type: string
                  additionalProperties: false
    put:
      tags:
        - Food
      summary: UpdateFood
      description: UpdateFood
      operationId: UpdateFood
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                price:
                  type: number
                  format: double
                inStock:
                  type: integer
                  format: int32
                minStock:
                  type: integer
                  description: Minimum amount to keep in stock
                  format: int32
                pictureUrl:
                  type: string
                code:
                  type: string
                description:
                  type: string
              additionalProperties: false
          text/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                price:
                  type: number
                  format: double
                inStock:
                  type: integer
                  format: int32
                minStock:
                  type: integer
                  description: Minimum amount to keep in stock
                  format: int32
                pictureUrl:
                  type: string
                code:
                  type: string
                description:
                  type: string
              additionalProperties: false
          application/*+json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                price:
                  type: number
                  format: double
                inStock:
                  type: integer
                  format: int32
                minStock:
                  type: integer
                  description: Minimum amount to keep in stock
                  format: int32
                pictureUrl:
                  type: string
                code:
                  type: string
                description:
                  type: string
              additionalProperties: false
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  price:
                    type: number
                    format: double
                  inStock:
                    type: integer
                    format: int32
                  minStock:
                    type: integer
                    description: Minimum amount to keep in stock
                    format: int32
                  pictureUrl:
                    type: string
                  code:
                    type: string
                  description:
                    type: string
                additionalProperties: false
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  price:
                    type: number
                    format: double
                  inStock:
                    type: integer
                    format: int32
                  minStock:
                    type: integer
                    description: Minimum amount to keep in stock
                    format: int32
                  pictureUrl:
                    type: string
                  code:
                    type: string
                  description:
                    type: string
                additionalProperties: false
            text/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  price:
                    type: number
                    format: double
                  inStock:
                    type: integer
                    format: int32
                  minStock:
                    type: integer
                    description: Minimum amount to keep in stock
                    format: int32
                  pictureUrl:
                    type: string
                  code:
                    type: string
                  description:
                    type: string
                additionalProperties: false
    post:
      tags:
        - Food
      summary: Add food
      description: Add food
      operationId: AddFood
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                price:
                  type: number
                  format: double
                inStock:
                  type: integer
                  format: int32
                minStock:
                  type: integer
                  description: Minimum amount to keep in stock
                  format: int32
                pictureUrl:
                  type: string
                code:
                  type: string
                description:
                  type: string
              additionalProperties: false
          text/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                price:
                  type: number
                  format: double
                inStock:
                  type: integer
                  format: int32
                minStock:
                  type: integer
                  description: Minimum amount to keep in stock
                  format: int32
                pictureUrl:
                  type: string
                code:
                  type: string
                description:
                  type: string
              additionalProperties: false
          application/*+json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                price:
                  type: number
                  format: double
                inStock:
                  type: integer
                  format: int32
                minStock:
                  type: integer
                  description: Minimum amount to keep in stock
                  format: int32
                pictureUrl:
                  type: string
                code:
                  type: string
                description:
                  type: string
              additionalProperties: false
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  price:
                    type: number
                    format: double
                  inStock:
                    type: integer
                    format: int32
                  minStock:
                    type: integer
                    description: Minimum amount to keep in stock
                    format: int32
                  pictureUrl:
                    type: string
                  code:
                    type: string
                  description:
                    type: string
                additionalProperties: false
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  price:
                    type: number
                    format: double
                  inStock:
                    type: integer
                    format: int32
                  minStock:
                    type: integer
                    description: Minimum amount to keep in stock
                    format: int32
                  pictureUrl:
                    type: string
                  code:
                    type: string
                  description:
                    type: string
                additionalProperties: false
            text/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  price:
                    type: number
                    format: double
                  inStock:
                    type: integer
                    format: int32
                  minStock:
                    type: integer
                    description: Minimum amount to keep in stock
                    format: int32
                  pictureUrl:
                    type: string
                  code:
                    type: string
                  description:
                    type: string
                additionalProperties: false
  '/Food/{id}':
    get:
      tags:
        - Food
      summary: GetFoodByID
      description: GetFoodByID
      operationId: GetFoodByID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  price:
                    type: number
                    format: double
                  inStock:
                    type: integer
                    format: int32
                  minStock:
                    type: integer
                    description: Minimum amount to keep in stock
                    format: int32
                  pictureUrl:
                    type: string
                  code:
                    type: string
                  description:
                    type: string
                additionalProperties: false
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  price:
                    type: number
                    format: double
                  inStock:
                    type: integer
                    format: int32
                  minStock:
                    type: integer
                    description: Minimum amount to keep in stock
                    format: int32
                  pictureUrl:
                    type: string
                  code:
                    type: string
                  description:
                    type: string
                additionalProperties: false
            text/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  price:
                    type: number
                    format: double
                  inStock:
                    type: integer
                    format: int32
                  minStock:
                    type: integer
                    description: Minimum amount to keep in stock
                    format: int32
                  pictureUrl:
                    type: string
                  code:
                    type: string
                  description:
                    type: string
                additionalProperties: false
components: { }